### ISSUE TITLE
QR Codes

### ISSUE THREAD

**Issue by Jikou21C** [benl23x5/dojo#26]
Hi Ben we had talked about QR codes and I thought it would be good if the students use their phone to read a QR Code and "mark" their attendance. It’s would also be good if this could run in tandem with instructor attendance input? that way the instructor can mark someone in who can't do it by QR code but also see who has marked themselves in and make changes if needed.

**Comment by benl23x5** [comment]
Right now the class record is used as a template for events, but to manage QR codes the event record should hold the class id. We can distribute a QR code for each class, but then attendees added via the QR code need to be attached to the correct event.

**Comment by Jikou21C** [comment]
When you say "class record", are these the attendees added via Edit Event? How are attendees added via QR code attached to the correct event?

**Comment by benl23x5** [comment]
Scanning the QR code now goes to a registration page where anyone can add new names. In on this page names can be added but not removed. Mistaken names should be removed by the event owner.
