### ISSUE TITLE
adding attendees

### ISSUE THREAD

**Issue by Jikou21C** [benl23x5/dojo#27]
It would be helpful if typing a name into the attendees field would suggest names matched in the database.

**Comment by benl23x5** [comment]
If you type a name into the box and press enter, it should suggest people whose first or last names start with that prefix. It will also disambiguate on initials eg "ben l".

**Comment by benl23x5** [comment]
Getting realtime suggestions would be more development work, but I agree we at least need some inline documentation about how to use the current system.
