### ISSUE TITLE
type (dojo, ttc etc) Field

### ISSUE THREAD

**Issue by Jikou21C** [benl23x5/dojo#28]
It would be helpful if typing into the type field would suggest dojo name matched in the database.

**Comment by benl23x5** [comment]
I’ll add a dropdown selector box where the user can select the event type from a list.
We also don't want people entering random dojo names or class types, or misspelling "Leichhardt"

**Comment by benl23x5** [comment]
Dojo names, class types, and member levels are now specified by dropdowns. The possible values are read from a table in the db.
