### ISSUE TITLE
Unable to edit attendees

### ISSUE THREAD

**Issue by mskierski** [benl23x5/dojo#84]
1. Once registration codes were issued on Sunday 22nd, only a single student used the mobile phone to register attendance.
2. The class was correctly created with default teacher and a single student
3. I'm unable to add any other students as Edit Attendees menu is no longer available

**Comment by benl23x5** [comment]
I fixed this. The site now knows about people who have delegated authority to manage attendance records, but are not listed as the default class owner. You should be able to edit the attendance records for the Saturday and Sunday classes now.

Let me know if there are other delegations that should be added.
